version: '3.1'

services:
  db-dev:
    extends:
      file: docker-compose.base.yml
      service: db
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
